<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('paises')->insert([
            [ 'id' => '1' , 'name' => 'Argentina' ],
            [ 'id' => '2' , 'name' => 'Afganistán' ],
            [ 'id' => '3' , 'name' => 'Albania' ],
            [ 'id' => '4' , 'name' => 'Alemania' ],
            [ 'id' => '5' , 'name' => 'Andorra' ],
            [ 'id' => '6' , 'name' => 'Angola' ],
            [ 'id' => '7' , 'name' => 'Antigua y Barbuda' ],
            [ 'id' => '8' , 'name' => 'Arabia Saudita' ],
            [ 'id' => '9' , 'name' => 'Argelia' ],
            [ 'id' => '10' , 'name' => 'Armenia' ],
            [ 'id' => '11' , 'name' => 'Australia' ],
            [ 'id' => '12' , 'name' => 'Austria' ],
            [ 'id' => '13' , 'name' => 'Azerbaiyán' ],
            [ 'id' => '14' , 'name' => 'Bahamas' ],
            [ 'id' => '15' , 'name' => 'Bangladés' ],
            [ 'id' => '16' , 'name' => 'Barbados' ],
            [ 'id' => '17' , 'name' => 'Baréin' ],
            [ 'id' => '18' , 'name' => 'Bélgica' ],
            [ 'id' => '19' , 'name' => 'Belice' ],
            [ 'id' => '20' , 'name' => 'Benín' ],
            [ 'id' => '21' , 'name' => 'Bielorrusia' ],
            [ 'id' => '22' , 'name' => 'Birmania' ],
            [ 'id' => '23' , 'name' => 'Bolivia' ],
            [ 'id' => '24' , 'name' => 'Bosnia y Herzegovina' ],
            [ 'id' => '25' , 'name' => 'Botsuana' ],
            [ 'id' => '26' , 'name' => 'Brasil' ],
            [ 'id' => '27' , 'name' => 'Brunéi' ],
            [ 'id' => '28' , 'name' => 'Bulgaria' ],
            [ 'id' => '29' , 'name' => 'Burkina Faso' ],
            [ 'id' => '30' , 'name' => 'Burundi' ],
            [ 'id' => '31' , 'name' => 'Bután' ],
            [ 'id' => '32' , 'name' => 'Cabo Verde' ],
            [ 'id' => '33' , 'name' => 'Camboya' ],
            [ 'id' => '34' , 'name' => 'Camerún' ],
            [ 'id' => '35' , 'name' => 'Canadá' ],
            [ 'id' => '36' , 'name' => 'Catar' ],
            [ 'id' => '37' , 'name' => 'Chad' ],
            [ 'id' => '38' , 'name' => 'Chile' ],
            [ 'id' => '39' , 'name' => 'China' ],
            [ 'id' => '40' , 'name' => 'Chipre' ],
            [ 'id' => '41' , 'name' => 'Ciudad del Vaticano' ],
            [ 'id' => '42' , 'name' => 'Colombia' ],
            [ 'id' => '43' , 'name' => 'Comoras' ],
            [ 'id' => '44' , 'name' => 'Corea del Norte' ],
            [ 'id' => '45' , 'name' => 'Corea del Sur' ],
            [ 'id' => '46' , 'name' => 'Costa de Marfil' ],
            [ 'id' => '47' , 'name' => 'Costa Rica' ],
            [ 'id' => '48' , 'name' => 'Croacia' ],
            [ 'id' => '49' , 'name' => 'Cuba' ],
            [ 'id' => '50' , 'name' => 'Dinamarca' ],
            [ 'id' => '51' , 'name' => 'Dominica' ],
            [ 'id' => '52' , 'name' => 'Ecuador' ],
            [ 'id' => '53' , 'name' => 'Egipto' ],
            [ 'id' => '54' , 'name' => 'El Salvador' ],
            [ 'id' => '55' , 'name' => 'Emiratos Árabes Unidos' ],
            [ 'id' => '56' , 'name' => 'Eritrea' ],
            [ 'id' => '57' , 'name' => 'Eslovaquia' ],
            [ 'id' => '58' , 'name' => 'Eslovenia' ],
            [ 'id' => '59' , 'name' => 'España' ],
            [ 'id' => '60' , 'name' => 'Estados Unidos' ],
            [ 'id' => '61' , 'name' => 'Estonia' ],
            [ 'id' => '62' , 'name' => 'Etiopía' ],
            [ 'id' => '63' , 'name' => 'Filipinas' ],
            [ 'id' => '64' , 'name' => 'Finlandia' ],
            [ 'id' => '65' , 'name' => 'Fiyi' ],
            [ 'id' => '66' , 'name' => 'Francia' ],
            [ 'id' => '67' , 'name' => 'Gabón' ],
            [ 'id' => '68' , 'name' => 'Gambia' ],
            [ 'id' => '69' , 'name' => 'Georgia' ],
            [ 'id' => '70' , 'name' => 'Ghana' ],
            [ 'id' => '71' , 'name' => 'Granada' ],
            [ 'id' => '72' , 'name' => 'Grecia' ],
            [ 'id' => '73' , 'name' => 'Guatemala' ],
            [ 'id' => '74' , 'name' => 'Guyana' ],
            [ 'id' => '75' , 'name' => 'Guinea' ],
            [ 'id' => '76' , 'name' => 'Guinea ecuatorial' ],
            [ 'id' => '77' , 'name' => 'Guinea-Bisáu' ],
            [ 'id' => '78' , 'name' => 'Haití' ],
            [ 'id' => '79' , 'name' => 'Honduras' ],
            [ 'id' => '80' , 'name' => 'Hungría' ],
            [ 'id' => '81' , 'name' => 'India' ],
            [ 'id' => '82' , 'name' => 'Indonesia' ],
            [ 'id' => '83' , 'name' => 'Irak' ],
            [ 'id' => '84' , 'name' => 'Irán' ],
            [ 'id' => '85' , 'name' => 'Irlanda' ],
            [ 'id' => '86' , 'name' => 'Islandia' ],
            [ 'id' => '87' , 'name' => 'Islas Marshall' ],
            [ 'id' => '88' , 'name' => 'Islas Salomón' ],
            [ 'id' => '89' , 'name' => 'Israel' ],
            [ 'id' => '90' , 'name' => 'Italia' ],
            [ 'id' => '91' , 'name' => 'Jamaica' ],
            [ 'id' => '92' , 'name' => 'Japón' ],
            [ 'id' => '93' , 'name' => 'Jordania' ],
            [ 'id' => '94' , 'name' => 'Kazajistán' ],
            [ 'id' => '95' , 'name' => 'Kenia' ],
            [ 'id' => '96' , 'name' => 'Kirguistán' ],
            [ 'id' => '97' , 'name' => 'Kiribati' ],
            [ 'id' => '98' , 'name' => 'Kuwait' ],
            [ 'id' => '99' , 'name' => 'Laos' ],
            [ 'id' => '100' , 'name' => 'Lesoto' ],
            [ 'id' => '101' , 'name' => 'Letonia' ],
            [ 'id' => '102' , 'name' => 'Líbano' ],
            [ 'id' => '103' , 'name' => 'Liberia' ],
            [ 'id' => '104' , 'name' => 'Libia' ],
            [ 'id' => '105' , 'name' => 'Liechtenstein' ],
            [ 'id' => '106' , 'name' => 'Lituania' ],
            [ 'id' => '107' , 'name' => 'Luxemburgo' ],
            [ 'id' => '108' , 'name' => 'Macedonia del Norte' ],
            [ 'id' => '109' , 'name' => 'Madagascar' ],
            [ 'id' => '110' , 'name' => 'Malasia' ],
            [ 'id' => '111' , 'name' => 'Malaui' ],
            [ 'id' => '112' , 'name' => 'Maldivas' ],
            [ 'id' => '113' , 'name' => 'Malí' ],
            [ 'id' => '114' , 'name' => 'Malta' ],
            [ 'id' => '115' , 'name' => 'Marruecos' ],
            [ 'id' => '116' , 'name' => 'Mauricio' ],
            [ 'id' => '117' , 'name' => 'Mauritania' ],
            [ 'id' => '118' , 'name' => 'México' ],
            [ 'id' => '119' , 'name' => 'Micronesia' ],
            [ 'id' => '120' , 'name' => 'Moldavia' ],
            [ 'id' => '121' , 'name' => 'Mónaco' ],
            [ 'id' => '122' , 'name' => 'Mongolia' ],
            [ 'id' => '123' , 'name' => 'Montenegro' ],
            [ 'id' => '124' , 'name' => 'Mozambique' ],
            [ 'id' => '125' , 'name' => 'Namibia' ],
            [ 'id' => '126' , 'name' => 'Nauru' ],
            [ 'id' => '127' , 'name' => 'Nepal' ],
            [ 'id' => '128' , 'name' => 'Nicaragua' ],
            [ 'id' => '129' , 'name' => 'Níger' ],
            [ 'id' => '130' , 'name' => 'Nigeria' ],
            [ 'id' => '131' , 'name' => 'Noruega' ],
            [ 'id' => '132' , 'name' => 'Nueva Zelanda' ],
            [ 'id' => '133' , 'name' => 'Omán' ],
            [ 'id' => '134' , 'name' => 'Países Bajos' ],
            [ 'id' => '135' , 'name' => 'Pakistán' ],
            [ 'id' => '136' , 'name' => 'Palaos' ],
            [ 'id' => '137' , 'name' => 'Panamá' ],
            [ 'id' => '138' , 'name' => 'Papúa Nueva Guinea' ],
            [ 'id' => '139' , 'name' => 'Paraguay' ],
            [ 'id' => '140' , 'name' => 'Perú' ],
            [ 'id' => '141' , 'name' => 'Polonia' ],
            [ 'id' => '142' , 'name' => 'Portugal' ],
            [ 'id' => '143' , 'name' => 'Reino Unido' ],
            [ 'id' => '144' , 'name' => 'República Centroafricana' ],
            [ 'id' => '145' , 'name' => 'República Checa' ],
            [ 'id' => '146' , 'name' => 'República del Congo' ],
            [ 'id' => '147' , 'name' => 'República Democrática del Congo' ],
            [ 'id' => '148' , 'name' => 'República Dominicana' ],
            [ 'id' => '149' , 'name' => 'Ruanda' ],
            [ 'id' => '150' , 'name' => 'Rumanía' ],
            [ 'id' => '151' , 'name' => 'Rusia' ],
            [ 'id' => '152' , 'name' => 'Samoa' ],
            [ 'id' => '153' , 'name' => 'San Cristóbal y Nieves' ],
            [ 'id' => '154' , 'name' => 'San Marino' ],
            [ 'id' => '155' , 'name' => 'San Vicente y las Granadinas' ],
            [ 'id' => '156' , 'name' => 'Santa Lucía' ],
            [ 'id' => '157' , 'name' => 'Santo Tomé y Príncipe' ],
            [ 'id' => '158' , 'name' => 'Senegal' ],
            [ 'id' => '159' , 'name' => 'Serbia' ],
            [ 'id' => '160' , 'name' => 'Seychelles' ],
            [ 'id' => '161' , 'name' => 'Sierra Leona' ],
            [ 'id' => '162' , 'name' => 'Singapur' ],
            [ 'id' => '163' , 'name' => 'Siria' ],
            [ 'id' => '164' , 'name' => 'Somalia' ],
            [ 'id' => '165' , 'name' => 'Sri Lanka' ],
            [ 'id' => '166' , 'name' => 'Suazilandia' ],
            [ 'id' => '167' , 'name' => 'Sudáfrica' ],
            [ 'id' => '168' , 'name' => 'Sudán' ],
            [ 'id' => '169' , 'name' => 'Sudán del Sur' ],
            [ 'id' => '170' , 'name' => 'Suecia' ],
            [ 'id' => '171' , 'name' => 'Suiza' ],
            [ 'id' => '172' , 'name' => 'Surinam' ],
            [ 'id' => '173' , 'name' => 'Tailandia' ],
            [ 'id' => '174' , 'name' => 'Tanzania' ],
            [ 'id' => '175' , 'name' => 'Tayikistán' ],
            [ 'id' => '176' , 'name' => 'Timor Oriental' ],
            [ 'id' => '177' , 'name' => 'Togo' ],
            [ 'id' => '178' , 'name' => 'Tonga' ],
            [ 'id' => '179' , 'name' => 'Trinidad y Tobago' ],
            [ 'id' => '180' , 'name' => 'Túnez' ],
            [ 'id' => '181' , 'name' => 'Turkmenistán' ],
            [ 'id' => '182' , 'name' => 'Turquía' ],
            [ 'id' => '183' , 'name' => 'Tuvalu' ],
            [ 'id' => '184' , 'name' => 'Ucrania' ],
            [ 'id' => '185' , 'name' => 'Uganda' ],
            [ 'id' => '186' , 'name' => 'Uruguay' ],
            [ 'id' => '187' , 'name' => 'Uzbekistán' ],
            [ 'id' => '188' , 'name' => 'Vanuatu' ],
            [ 'id' => '189' , 'name' => 'Venezuela' ],
            [ 'id' => '190' , 'name' => 'Vietnam' ],
            [ 'id' => '191' , 'name' => 'Yemen' ],
            [ 'id' => '192' , 'name' => 'Yibuti' ],
            [ 'id' => '193' , 'name' => 'Zambia' ],
            [ 'id' => '194' , 'name' => 'Zimbabue' ]
        ]);
    }
}
