/*https://codigo-postal.co/argentina/cp/3603/*/
UPDATE localidads SET name = UPPER('Las Chuñas') WHERE id = '27';
UPDATE localidads SET name = UPPER('Chañar Ladeado') WHERE id = '64';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '316';
UPDATE localidads SET name = UPPER('Villa Cañas') WHERE id = '524';
UPDATE localidads SET name = UPPER('Piñero') WHERE id = '22789';

UPDATE localidads SET name = UPPER('La Niña') WHERE id = '936';
UPDATE localidads SET name = UPPER('Piñeyro') WHERE id = '1070';
UPDATE localidads SET name = UPPER('Vaña') WHERE id = '1114';
UPDATE localidads SET name = UPPER('Puente Cañete') WHERE id = '1191';
UPDATE localidads SET name = UPPER('Viña') WHERE id = '1194';
UPDATE localidads SET name = UPPER('Arroyo Ñacurutu Chico') WHERE id = '1276';
UPDATE localidads SET name = UPPER('Piñeyro') WHERE id = '1538';
UPDATE localidads SET name = UPPER('Quiñihual Estacion') WHERE id = '1541';
UPDATE localidads SET name = UPPER('Goñi') WHERE id = '1686';
UPDATE localidads SET name = UPPER('Piñeiro') WHERE id = '1987';
UPDATE localidads SET name = UPPER('Durañona') WHERE id = '2110';
UPDATE localidads SET name = UPPER('Muñoz') WHERE id = '2127';
UPDATE localidads SET name = UPPER('Albariño') WHERE id = 'ALBARI';
UPDATE localidads SET name = UPPER('Arroyo Ñacurutu') WHERE id = '2738';

UPDATE localidads SET name = UPPER('Jaguel Campo Monte') WHERE id = '2858';
UPDATE localidads SET name = UPPER('Peñas Blancas') WHERE id = '2999';

UPDATE localidads SET name = UPPER('El Ñango') WHERE id = '3150';
UPDATE localidads SET name = UPPER('El Cañito') WHERE id = '3243';
UPDATE localidads SET name = UPPER('Baños Lunlunta') WHERE id = '3329';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '3461';
UPDATE localidads SET name = UPPER('Baños de Capiz') WHERE id = '13566';
UPDATE localidads SET name = UPPER('Baños la Salada') WHERE id = '13567';
UPDATE localidads SET name = UPPER('La Seña') WHERE id = '13012';
UPDATE localidads SET name = UPPER('Bañado Verde') WHERE id = '13039';
UPDATE localidads SET name = UPPER('Chañaral Redondo') WHERE id = '13049';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '13160';
UPDATE localidads SET name = UPPER('Baños de Azufre') WHERE id = '15999';
UPDATE localidads SET name = UPPER('El Chañar') WHERE id = '15486';
UPDATE localidads SET name = UPPER('Peña') WHERE id = '14006';
UPDATE localidads SET name = UPPER('La Leña') WHERE id = '3697';
UPDATE localidads SET name = UPPER('Ipiña') WHERE id = '3887';
UPDATE localidads SET name = UPPER('Quiñi Malal') WHERE id = '4194';

UPDATE localidads SET name = UPPER('Añelo') WHERE id = '4531';
UPDATE localidads SET name = UPPER('Peña Colorada') WHERE id = '4614';
UPDATE localidads SET name = UPPER('Sañico') WHERE id = '4619';
UPDATE localidads SET name = UPPER('Reñileo') WHERE id = '4765';
UPDATE localidads SET name = UPPER('Goñi Co') WHERE id = '4872';
UPDATE localidads SET name = UPPER('Lago Ñorquinco') WHERE id = '22841';

UPDATE localidads SET name = UPPER('Las Cañitas') WHERE id = '5312';
UPDATE localidads SET name = UPPER('Monseñor de Andrea') WHERE id = '5314';
UPDATE localidads SET name = UPPER('El Bañadero') WHERE id = '19264';
UPDATE localidads SET name = UPPER('Rincon Ñaro') WHERE id = '19381';
UPDATE localidads SET name = UPPER('El Cañon') WHERE id = '13714';
UPDATE localidads SET name = UPPER('Rincon Ñandu') WHERE id = '18440';
UPDATE localidads SET name = UPPER('El Ñandu') WHERE id = '18359';
UPDATE localidads SET name = UPPER('Las Cañitas') WHERE id = '18104';

UPDATE localidads SET name = UPPER('Las Peñas') WHERE id = '5514';
UPDATE localidads SET name = UPPER('Chañar') WHERE id = '5525';
UPDATE localidads SET name = UPPER('Chañar Feliciano') WHERE id = '5538';
UPDATE localidads SET name = UPPER('Chañar Maria Grande Primera') WHERE id = '5763';
UPDATE localidads SET name = UPPER('Gobernador Sola') WHERE id = '5822';
UPDATE localidads SET name = UPPER('Gobernador Sola') WHERE id = '15740';
UPDATE localidads SET name = UPPER('Puente Ñancay') WHERE id = '14623';
UPDATE localidads SET name = UPPER('Bañadero Oficial las Galarzas') WHERE id = '14772';
UPDATE localidads SET name = UPPER('Bañadero Oficial Burgos') WHERE id = '15337';

UPDATE localidads SET name = UPPER('Bañado Grande') WHERE id = '6051';
UPDATE localidads SET name = UPPER('Campiña de Bonpland') WHERE id = '6057';
UPDATE localidads SET name = UPPER('Campiña Grande') WHERE id = '6058';
UPDATE localidads SET name = UPPER('Piñalito Norte') WHERE id = '6154';
UPDATE localidads SET name = UPPER('Piñalito Sur') WHERE id = '6155';
UPDATE localidads SET name = UPPER('Cuña Piru') WHERE id = '6211';
UPDATE localidads SET name = UPPER('Colonia Ñacangazu') WHERE id = '6281';
UPDATE localidads SET name = UPPER('Cuña Pora') WHERE id = '16075';
UPDATE localidads SET name = UPPER('Doña Maria') WHERE id = '16120';

UPDATE localidads SET name = UPPER('Cuña Suegra') WHERE id = '6472';
UPDATE localidads SET name = UPPER('Bañado San Antonio') WHERE id = '6599';
UPDATE localidads SET name = UPPER('Acuña') WHERE id = '6724';
UPDATE localidads SET name = UPPER('El Ñandubay') WHERE id = '13595';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '13640';
UPDATE localidads SET name = UPPER('Acuña Cue') WHERE id = '15556';
UPDATE localidads SET name = UPPER('Bañado Norte') WHERE id = '13262';
UPDATE localidads SET name = UPPER('Bañado Sur') WHERE id = '13264';
UPDATE localidads SET name = UPPER('Arañita') WHERE id = '13355';

UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '6996';
UPDATE localidads SET name = UPPER('La Peña') WHERE id = '7074';
UPDATE localidads SET name = UPPER('Peñaflor') WHERE id = '7093';
UPDATE localidads SET name = UPPER('Chañaryaco') WHERE id = '7118';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '7189';
UPDATE localidads SET name = UPPER('La Viña') WHERE id = '7200';
UPDATE localidads SET name = UPPER('Vicuña Pampa') WHERE id = '7226';
UPDATE localidads SET name = UPPER('Los Chañaritos') WHERE id = '7233';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '7245';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '7239';
UPDATE localidads SET name = UPPER('Chañar Laguna') WHERE id = '7286';
UPDATE localidads SET name = UPPER('Bañado de Divisadero') WHERE id = '7352';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '7364';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '7410';
UPDATE localidads SET name = UPPER('La Peña') WHERE id = '7420';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '7614';
UPDATE localidads SET name = UPPER('Las Peñas') WHERE id = '7431';
UPDATE localidads SET name = UPPER('Cerviño') WHERE id = '7481';
UPDATE localidads SET name = UPPER('Chañaritos') WHERE id = '7357';
UPDATE localidads SET name = UPPER('Chafiñan') WHERE id = '7559';
UPDATE localidads SET name = UPPER('Chañar Punco') WHERE id = '7560';
UPDATE localidads SET name = UPPER('Bañado de Ovanta') WHERE id = '7601';
UPDATE localidads SET name = UPPER('Baños Termales') WHERE id = '7646';
UPDATE localidads SET name = UPPER('El Peñon') WHERE id = '7657';
UPDATE localidads SET name = UPPER('La Cañada Larga') WHERE id = '7666';
UPDATE localidads SET name = UPPER('Peñas Blancas') WHERE id = '7702';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '7720';
UPDATE localidads SET name = UPPER('Peñon') WHERE id = '12804';

UPDATE localidads SET name = UPPER('El Ñandubay') WHERE id = '7986';
UPDATE localidads SET name = UPPER('La Ñata') WHERE id = '7990';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '8036';
UPDATE localidads SET name = UPPER('El Cañon') WHERE id = '13453';
UPDATE localidads SET name = UPPER('Doña Paula') WHERE id = '14234';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '14264';
UPDATE localidads SET name = UPPER('Ntra Señora de la Concepcion') WHERE id = '14637';

UPDATE localidads SET name = UPPER('Chañar Muyo') WHERE id = '8100';
UPDATE localidads SET name = UPPER('Viñaco') WHERE id = '8271';
UPDATE localidads SET name = UPPER('La Viña') WHERE id = '8299';
UPDATE localidads SET name = UPPER('Isla de Cañas') WHERE id = '8413';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '8460';
UPDATE localidads SET name = UPPER('Peñas Azules') WHERE id = '8464';
UPDATE localidads SET name = UPPER('Siñunto') WHERE id = '8475';
UPDATE localidads SET name = UPPER('Peñas Blancas') WHERE id = '8553';
UPDATE localidads SET name = UPPER('Las Cañitas') WHERE id = '8634';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '16454';
UPDATE localidads SET name = UPPER('Peñalva') WHERE id = '16731';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '16849';
UPDATE localidads SET name = UPPER('Chañar') WHERE id = '12694';
UPDATE localidads SET name = UPPER('Queñua') WHERE id = '17170';
UPDATE localidads SET name = UPPER('El Ñato') WHERE id = '17186';
UPDATE localidads SET name = UPPER('Baños Termales') WHERE id = '17235';
UPDATE localidads SET name = UPPER('Los Baños') WHERE id = '17266';
UPDATE localidads SET name = UPPER('Chañar Aguada') WHERE id = '12729';
UPDATE localidads SET name = UPPER('La Cabaña') WHERE id = '17365';
UPDATE localidads SET name = UPPER('Las Viñas') WHERE id = '17367';

UPDATE localidads SET name = UPPER('Chañar Taqueño') WHERE id = '8739';
UPDATE localidads SET name = UPPER('Chañar Via') WHERE id = '8740';
UPDATE localidads SET name = UPPER('Chañar Viejo') WHERE id = '8951';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '8769';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '9100';
UPDATE localidads SET name = UPPER('Chañaritos') WHERE id = '18418';
UPDATE localidads SET name = UPPER('Las Cañitas') WHERE id = '9111';
UPDATE localidads SET name = UPPER('Las Cañitas') WHERE id = '19582';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '9187';
UPDATE localidads SET name = UPPER('Bañado del Valle') WHERE id = '9217';
UPDATE localidads SET name = UPPER('Chañar Pago') WHERE id = '9230';
UPDATE localidads SET name = UPPER('Chañar Muya') WHERE id = '9231';
UPDATE localidads SET name = UPPER('Chañar Pozo') WHERE id = '19737';
UPDATE localidads SET name = UPPER('Chañarito') WHERE id = '19738';
UPDATE localidads SET name = UPPER('Chañarito') WHERE id = '19740';
UPDATE localidads SET name = UPPER('Las Cañadas') WHERE id = '9271';
UPDATE localidads SET name = UPPER('La Cañada Parada') WHERE id = '9535';
UPDATE localidads SET name = UPPER('Ingenio Ñuñorco') WHERE id = '9376';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '9518';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '9541';
UPDATE localidads SET name = UPPER('Los Chañares') WHERE id = '9548';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '9627';
UPDATE localidads SET name = UPPER('Las Cañitas') WHERE id = '19927';
UPDATE localidads SET name = UPPER('La Viñita') WHERE id = '19048';
UPDATE localidads SET name = UPPER('Peña Overa') WHERE id = '19074';
UPDATE localidads SET name = UPPER('Peña Picaza') WHERE id = '19076';
UPDATE localidads SET name = UPPER('Villa Muñecas') WHERE id = '19571';
UPDATE localidads SET name = UPPER('Chañar') WHERE id = '18414';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '18466';

UPDATE localidads SET name = UPPER('Las Cañadas') WHERE id = '9766';
UPDATE localidads SET name = UPPER('Peñas Blancas') WHERE id = '9805';
UPDATE localidads SET name = UPPER('Peñas Blancas') WHERE id = '19236';
UPDATE localidads SET name = UPPER('Paño') WHERE id = '9865';
UPDATE localidads SET name = UPPER('Muñayoc') WHERE id = '9927';
UPDATE localidads SET name = UPPER('Queñoal') WHERE id = '12660';
UPDATE localidads SET name = UPPER('Chañi') WHERE id = '18860';
UPDATE localidads SET name = UPPER('Chañar Solo') WHERE id = '19057';
UPDATE localidads SET name = UPPER('Chañaral') WHERE id = '19058';
UPDATE localidads SET name = UPPER('Peña Colorada') WHERE id = '19368';
UPDATE localidads SET name = UPPER('Chañarcito') WHERE id = '19431';
UPDATE localidads SET name = UPPER('Chañi Chico') WHERE id = '19432';

UPDATE localidads SET name = UPPER('Sañogasta') WHERE id = '10097';
UPDATE localidads SET name = UPPER('Rio de las Cañas') WHERE id = '10198';
UPDATE localidads SET name = UPPER('Chañar') WHERE id = '10213';
UPDATE localidads SET name = UPPER('Peñas Blancas') WHERE id = '10332';
UPDATE localidads SET name = UPPER('Señor de la Peña') WHERE id = '15860';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '15979';
UPDATE localidads SET name = UPPER('Chañarmuyo') WHERE id = '16274';
UPDATE localidads SET name = UPPER('Las Peñas') WHERE id = '12595';

UPDATE localidads SET name = UPPER('Chañar Pujio') WHERE id = '10398';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '10418';
UPDATE localidads SET name = UPPER('Añatuya') WHERE id = '10538';
UPDATE localidads SET name = UPPER('Doña Luisa') WHERE id = '10551';
UPDATE localidads SET name = UPPER('Chañar Pocito') WHERE id = '10706';
UPDATE localidads SET name = UPPER('Chañar Pozo') WHERE id = '10703';
UPDATE localidads SET name = UPPER('Chuña Albardon') WHERE id = '10608';
UPDATE localidads SET name = UPPER('Chañar Bajada') WHERE id = '10665';
UPDATE localidads SET name = UPPER('Chañar Esquina') WHERE id = '10666';
UPDATE localidads SET name = UPPER('Chañar Pozo') WHERE id = '10704';
UPDATE localidads SET name = UPPER('Chañar Pozo de Abajo') WHERE id = '10705';
UPDATE localidads SET name = UPPER('El Señuelo') WHERE id = '17537';
UPDATE localidads SET name = UPPER('El Añil') WHERE id = '17642';
UPDATE localidads SET name = UPPER('Añil') WHERE id = '17647';
UPDATE localidads SET name = UPPER('Chañar Yaco') WHERE id = '17751';
UPDATE localidads SET name = UPPER('Chañares Altos') WHERE id = '21425';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '17770';
UPDATE localidads SET name = UPPER('Wiñano') WHERE id = '21420';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '21453';
UPDATE localidads SET name = UPPER('Chañaritos') WHERE id = '17754';
UPDATE localidads SET name = UPPER('Wiñano') WHERE id = '22664';
UPDATE localidads SET name = UPPER('Guañagasta') WHERE id = '16664';
UPDATE localidads SET name = UPPER('El Cañon') WHERE id = '16765';
UPDATE localidads SET name = UPPER('Chañar Pujio') WHERE id = '18043';
UPDATE localidads SET name = UPPER('Señora Pujio') WHERE id = '21222';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '21274';
UPDATE localidads SET name = UPPER('Chañar Pozo') WHERE id = '21338';
UPDATE localidads SET name = UPPER('Los Caños') WHERE id = '22430';
UPDATE localidads SET name = UPPER('Los Caños') WHERE id = '21346';
UPDATE localidads SET name = UPPER('El Viñalito') WHERE id = '21441';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '22410';
UPDATE localidads SET name = UPPER('Chañar Sunichaj') WHERE id = '21615';
UPDATE localidads SET name = UPPER('Señora Pujio') WHERE id = '21744';
UPDATE localidads SET name = UPPER('Simbol Cañada') WHERE id = '21747';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '21781';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '21817';
UPDATE localidads SET name = UPPER('El Chañar') WHERE id = '22067';
UPDATE localidads SET name = UPPER('Sinchi Caña') WHERE id = '22080';
UPDATE localidads SET name = UPPER('Los Nuñez') WHERE id = '22473';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '22640';

UPDATE localidads SET name = UPPER('Bañado') WHERE id = '10811';
UPDATE localidads SET name = UPPER('Peñon Colorado') WHERE id = '10908';
UPDATE localidads SET name = UPPER('Bañado Lindo') WHERE id = '10812';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '10833';
UPDATE localidads SET name = UPPER('El Chañar') WHERE id = '10837';
UPDATE localidads SET name = UPPER('Bañadito') WHERE id = '11456';
UPDATE localidads SET name = UPPER('Bañado de Cautana') WHERE id = '11457';
UPDATE localidads SET name = UPPER('Tres Cañadas') WHERE id = '10945';
UPDATE localidads SET name = UPPER('Caleras Cañada Grande') WHERE id = '11035';
UPDATE localidads SET name = UPPER('Laguna de la Cañada') WHERE id = '11720';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '11725';
UPDATE localidads SET name = UPPER('Chañaritos') WHERE id = '11038';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '11047';
UPDATE localidads SET name = UPPER('Cruz de Caña') WHERE id = '11133';
UPDATE localidads SET name = UPPER('El Chañar') WHERE id = '11139';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '11160';
UPDATE localidads SET name = UPPER('Las Peñas') WHERE id = '11174';
UPDATE localidads SET name = UPPER('El Chañar') WHERE id = '11374';
UPDATE localidads SET name = UPPER('Los Chañares') WHERE id = '11316';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '11394';
UPDATE localidads SET name = UPPER('El Chañar') WHERE id = '11546';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '11566';
UPDATE localidads SET name = UPPER('Las Tres Cañadas') WHERE id = '11581';
UPDATE localidads SET name = UPPER('Tres Cañadas') WHERE id = '11622';
UPDATE localidads SET name = UPPER('Las Cañitas') WHERE id = '17049';
UPDATE localidads SET name = UPPER('Bañadito Viejo') WHERE id = '16875';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '16948';

UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '11822';
UPDATE localidads SET name = UPPER('Baños de la Laja') WHERE id = '11818';
UPDATE localidads SET name = UPPER('Chañar Seco') WHERE id = '14437';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '14462';
UPDATE localidads SET name = UPPER('Peñasquito') WHERE id = '14516';
UPDATE localidads SET name = UPPER('Los Viñedos') WHERE id = '14569';
UPDATE localidads SET name = UPPER('Baños Centenario') WHERE id = '14576';
UPDATE localidads SET name = UPPER('Baños de los Despoblados') WHERE id = '14577';
UPDATE localidads SET name = UPPER('Baños de San Crispin') WHERE id = '11899';
UPDATE localidads SET name = UPPER('Huañizuil') WHERE id = '14667';
UPDATE localidads SET name = UPPER('Las Peñitas') WHERE id = '14683';
UPDATE localidads SET name = UPPER('Peñasco Colorado') WHERE id = '14710';
UPDATE localidads SET name = UPPER('Peñasquito') WHERE id = '14712';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '14677';
UPDATE localidads SET name = UPPER('Baños Pismanta') WHERE id = '11900';
UPDATE localidads SET name = UPPER('Guañizul') WHERE id = '11911';
UPDATE localidads SET name = UPPER('Chañar Pintado') WHERE id = '14773';
UPDATE localidads SET name = UPPER('Cerro la Cañada Amarilla') WHERE id = '14780';
UPDATE localidads SET name = UPPER('Villa Muñoz') WHERE id = '14975';
UPDATE localidads SET name = UPPER('Baños del Cerro') WHERE id = '15015';
UPDATE localidads SET name = UPPER('Los Viñedos') WHERE id = '12048';
UPDATE localidads SET name = UPPER('Chañar') WHERE id = '12095';

UPDATE localidads SET name = UPPER('Las Peñas Sud') WHERE id = '18069';
UPDATE localidads SET name = UPPER('Las Peñas Norte') WHERE id = '18425';
UPDATE localidads SET name = UPPER('Bañado del Fuerte') WHERE id = '18613';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '18682';
UPDATE localidads SET name = UPPER('Cruz de Caña') WHERE id = '12324';
UPDATE localidads SET name = UPPER('Chañar Viejo') WHERE id = '18639';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '18757';
UPDATE localidads SET name = UPPER('Churqui Cañada') WHERE id = '20689';
UPDATE localidads SET name = UPPER('Las Cañitas') WHERE id = '18041';
UPDATE localidads SET name = UPPER('El Bañado') WHERE id = '21054';
UPDATE localidads SET name = UPPER('Colonia Cañadon') WHERE id = '18250';
UPDATE localidads SET name = UPPER('Despeñaderos') WHERE id = '12362';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '18341';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '19348';
UPDATE localidads SET name = UPPER('Los Chañares') WHERE id = '18453';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '18734';
UPDATE localidads SET name = UPPER('Estancia las Cañas') WHERE id = '19240';
UPDATE localidads SET name = UPPER('Nuñez del Prado') WHERE id = '19588';
UPDATE localidads SET name = UPPER('Los Chañaritos') WHERE id = '19514';
UPDATE localidads SET name = UPPER('Los Chañares') WHERE id = '19566';
UPDATE localidads SET name = UPPER('Bañado de Paja') WHERE id = '19618';
UPDATE localidads SET name = UPPER('Niña Paula') WHERE id = '19749';
UPDATE localidads SET name = UPPER('Bañado de Soto') WHERE id = '19757';
UPDATE localidads SET name = UPPER('Los Chañaritos') WHERE id = '19956';
UPDATE localidads SET name = UPPER('Las Cañadas') WHERE id = '19943';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '19990';
UPDATE localidads SET name = UPPER('Las Cañadas') WHERE id = '19999';
UPDATE localidads SET name = UPPER('Las Cañitas') WHERE id = '20206';
UPDATE localidads SET name = UPPER('La Cañada Angosta') WHERE id = '20379';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '20436';
UPDATE localidads SET name = UPPER('Chuña Huasi') WHERE id = '20458';
UPDATE localidads SET name = UPPER('La Cañada Santa Cruz') WHERE id = '20710';
UPDATE localidads SET name = UPPER('La Cañada Grande') WHERE id = '20648';
UPDATE localidads SET name = UPPER('Las Cañas') WHERE id = '20721';
UPDATE localidads SET name = UPPER('Tala Cañada') WHERE id = '20829';
UPDATE localidads SET name = UPPER('Chañariaco') WHERE id = '20836';
UPDATE localidads SET name = UPPER('La Cañada') WHERE id = '20967';
UPDATE localidads SET name = UPPER('Chañaritos') WHERE id = '21043';
UPDATE localidads SET name = UPPER('Cruz de Caña') WHERE id = '22790';
